# Generated by scripts/update-formula.sh — do not edit by hand.
class ClaudeOpenaiProxy < Formula
  desc "OpenAI-compatible HTTP proxy backed by the Claude CLI"
  homepage "https://github.com/kpod13/claude-openai-proxy"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/kpod13/claude-openai-proxy/releases/download/v0.1.2/claude-openai-proxy_0.1.2_darwin_arm64.tar.gz"
      sha256 "a9e704a429d8d3e4e813269ad688cc69bd0abb192950fd5b5966eca6003924a0"
    end
    on_intel do
      url "https://github.com/kpod13/claude-openai-proxy/releases/download/v0.1.2/claude-openai-proxy_0.1.2_darwin_amd64.tar.gz"
      sha256 "a2a964856b3ac012783fbed5b3e3dc271a0edfd662d2c5859e430137da0277f4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kpod13/claude-openai-proxy/releases/download/v0.1.2/claude-openai-proxy_0.1.2_linux_arm64.tar.gz"
      sha256 "70cda407f9994cccb233fbdc2902a0612dba4ef5d342c9508b3ac19d3ca030ae"
    end
    on_intel do
      url "https://github.com/kpod13/claude-openai-proxy/releases/download/v0.1.2/claude-openai-proxy_0.1.2_linux_amd64.tar.gz"
      sha256 "6c64c023fae4759eb3ff34a4dba68e917d9ee92a30182cb760f096c8b0341e08"
    end
  end

  def install
    bin.install "claude-openai-proxy"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/claude-openai-proxy --version")
  end
end
